# Generated by Django 6.0.5 on 2026-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='secret',
        ),
        migrations.AddField(
            model_name='apikey',
            name='hashed_secret',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratelimit',
            name='requests_per_day',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='ratelimit',
            name='requests_per_hour',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='ratelimit',
            name='requests_per_minute',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.CharField(choices=[('price_alert', 'Price Alert'), ('portfolio_update', 'Portfolio Update'), ('risk_alert', 'Risk Alert'), ('market_open', 'Market Open'), ('market_close', 'Market Close'), ('score_updated', 'Score Updated'), ('anomaly_flagged', 'Anomaly Flagged')], max_length=50),
        ),
    ]
